import ExcelJS from "exceljs";
import type { ReconciliationRecord } from "@prisma/client";
import type { SupplierPayoutInvoiceRow } from "./pdf.js";

function shopName(): string {
  return process.env.SHOP_NAME ?? "Your Shop";
}

function toNum(value: unknown): number {
  const n = Number(value ?? 0);
  return Number.isFinite(n) ? n : 0;
}

interface ExcelMeta {
  generatedByName?: string | null;
}

function addReportHeader(sheet: ExcelJS.Worksheet, title: string, subtitle: string, meta: ExcelMeta, columnCount: number) {
  sheet.mergeCells(1, 1, 1, columnCount);
  const titleCell = sheet.getCell(1, 1);
  titleCell.value = shopName();
  titleCell.font = { bold: true, size: 14 };

  sheet.mergeCells(2, 1, 2, columnCount);
  const reportCell = sheet.getCell(2, 1);
  reportCell.value = title;
  reportCell.font = { bold: true, size: 12, color: { argb: "FF4F46E5" } };

  sheet.mergeCells(3, 1, 3, columnCount);
  sheet.getCell(3, 1).value = subtitle;

  sheet.mergeCells(4, 1, 4, columnCount);
  const generatedLine = `Generated: ${new Date().toLocaleString("en-GB")}${meta.generatedByName ? `  |  Generated by: ${meta.generatedByName}` : ""}`;
  sheet.getCell(4, 1).value = generatedLine;
  sheet.getCell(4, 1).font = { size: 9, color: { argb: "FF6B7280" } };

  sheet.addRow([]);
}

function styleHeaderRow(row: ExcelJS.Row) {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF4F46E5" } };
    cell.alignment = { vertical: "middle" };
  });
}

function styleTotalsRow(row: ExcelJS.Row) {
  row.eachCell((cell) => {
    cell.font = { bold: true };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF5F3FF" } };
  });
}

/* ── Sales Reconciliation Excel export ────────────────────────────────── */

export async function buildReconciliationExcel(
  records: ReconciliationRecord[],
  fromDateStr: string,
  toDateStr: string,
  meta: ExcelMeta = {},
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = shopName();
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Sales Reconciliation");
  const columns = [
    { header: "Date", key: "date", width: 14 },
    { header: "Staff", key: "staff", width: 16 },
    { header: "Shift", key: "shift", width: 12 },
    { header: "Manual Card", key: "manualCardAmount", width: 14 },
    { header: "Card Amount", key: "cardAmount", width: 14 },
    { header: "Last Safe", key: "lastSafe", width: 12 },
    { header: "Safe Drop", key: "safeDropAmount", width: 12 },
    { header: "Cashback", key: "cashback", width: 12 },
    { header: "Paypoint Payout", key: "paypointPayout", width: 14 },
    { header: "Instant Lottery Payout", key: "instantLotteryPayout", width: 18 },
    { header: "Lottery Payout", key: "lotteryPayout", width: 14 },
    { header: "News Voucher", key: "newsVoucher", width: 12 },
    { header: "DD Point", key: "ddPoint", width: 10 },
    { header: "Supplier Payout", key: "supplierInvoicesTotal", width: 14 },
    { header: "Lottery Value", key: "lotteryValue", width: 12 },
    { header: "Paypoint Value", key: "paypointValue", width: 14 },
    { header: "Summary Total", key: "summaryTotal", width: 14 },
    { header: "Z-Report Total", key: "zReportTotal", width: 14 },
    { header: "Difference", key: "difference", width: 12 },
    { header: "Committed By", key: "committedByName", width: 16 },
  ];

  addReportHeader(sheet, "Sales Reconciliation Report", `Date range: ${fromDateStr} to ${toDateStr}`, meta, columns.length);

  const headerRow = sheet.addRow(columns.map((c) => c.header));
  styleHeaderRow(headerRow);
  sheet.columns = columns.map((c) => ({ width: c.width }));

  let grand = {
    manualCardAmount: 0, cardAmount: 0, lastSafe: 0, safeDropAmount: 0, cashback: 0,
    paypointPayout: 0, instantLotteryPayout: 0, lotteryPayout: 0, newsVoucher: 0, ddPoint: 0,
    supplierInvoicesTotal: 0, lotteryValue: 0, paypointValue: 0, summaryTotal: 0, zReportTotal: 0, difference: 0,
  };

  for (const r of records) {
    const rowData = {
      date: r.date.toISOString().split("T")[0],
      staff: r.staffName ?? "",
      shift: r.shift ?? "",
      manualCardAmount: toNum(r.manualCardAmount),
      cardAmount: toNum(r.cardAmount),
      lastSafe: toNum(r.lastSafe),
      safeDropAmount: toNum(r.safeDropAmount),
      cashback: toNum(r.cashback),
      paypointPayout: toNum(r.paypointPayout),
      instantLotteryPayout: toNum(r.instantLotteryPayout),
      lotteryPayout: toNum(r.lotteryPayout),
      newsVoucher: toNum(r.newsVoucher),
      ddPoint: toNum(r.ddPoint),
      supplierInvoicesTotal: toNum(r.supplierInvoicesTotal),
      lotteryValue: toNum(r.lotteryValue),
      paypointValue: toNum(r.paypointValue),
      summaryTotal: toNum(r.summaryTotal),
      zReportTotal: toNum(r.zReportTotal),
      difference: toNum(r.difference),
      committedByName: r.committedByName ?? "",
    };
    sheet.addRow(Object.values(rowData));

    for (const key of Object.keys(grand) as Array<keyof typeof grand>) {
      grand[key] += rowData[key as keyof typeof rowData] as number;
    }
  }

  const totalsRow = sheet.addRow([
    "Grand Total", "", "",
    grand.manualCardAmount, grand.cardAmount, grand.lastSafe, grand.safeDropAmount, grand.cashback,
    grand.paypointPayout, grand.instantLotteryPayout, grand.lotteryPayout, grand.newsVoucher, grand.ddPoint,
    grand.supplierInvoicesTotal, grand.lotteryValue, grand.paypointValue, grand.summaryTotal, grand.zReportTotal, grand.difference, "",
  ]);
  styleTotalsRow(totalsRow);

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/* ── Supplier Payout Excel export ─────────────────────────────────────── */

export async function buildSupplierPayoutExcel(
  invoices: SupplierPayoutInvoiceRow[],
  fromDateStr: string,
  toDateStr: string,
  meta: ExcelMeta = {},
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = shopName();
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Supplier Payout");
  const columnCount = 5;
  addReportHeader(sheet, "Supplier Payout Report", `Date range: ${fromDateStr} to ${toDateStr}`, meta, columnCount);

  const headerRow = sheet.addRow(["Date", "Supplier", "Invoice No.", "Entered By", "Value"]);
  styleHeaderRow(headerRow);
  sheet.columns = [
    { width: 14 }, { width: 22 }, { width: 20 }, { width: 18 }, { width: 14 },
  ];

  const bySupplier = new Map<string, SupplierPayoutInvoiceRow[]>();
  for (const inv of invoices) {
    const list = bySupplier.get(inv.supplierName) ?? [];
    list.push(inv);
    bySupplier.set(inv.supplierName, list);
  }

  let grandTotal = 0;
  const supplierNames = Array.from(bySupplier.keys()).sort((a, b) => a.localeCompare(b));

  for (const supplierName of supplierNames) {
    const rows = bySupplier.get(supplierName)!;
    let supplierTotal = 0;
    for (const inv of rows) {
      supplierTotal += inv.value;
      sheet.addRow([inv.date, inv.supplierName, inv.invoiceNo, inv.enteredBy ?? "", inv.value]);
    }
    const supplierTotalRow = sheet.addRow(["", "", "", `${supplierName} Total`, supplierTotal]);
    styleTotalsRow(supplierTotalRow);
    grandTotal += supplierTotal;
  }

  sheet.addRow([]);
  const grandRow = sheet.addRow(["", "", "", "Grand Total", grandTotal]);
  grandRow.eachCell((cell) => {
    cell.font = { bold: true, size: 12 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E7FF" } };
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
