import PDFDocument from "pdfkit";
import type { ReconciliationRecord } from "@prisma/client";

function shopName(): string {
  return process.env.SHOP_NAME ?? "Your Shop";
}

function fmtGBP(value: unknown): string {
  const n = Number(value ?? 0);
  return `£${n.toFixed(2)}`;
}

function fmtDateStr(date: Date): string {
  return date.toISOString().split("T")[0];
}

export interface PdfMeta {
  generatedByName?: string | null;
}

export interface TableColumn {
  label: string;
  width: number;
  align?: "left" | "right" | "center";
}

export interface TableRow {
  cells: string[];
  bold?: boolean;
  highlight?: boolean;
}

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 pt
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const FOOTER_Y = 780;

function collectPdf(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.end();
  });
}

function newDocument(): PDFKit.PDFDocument {
  return new PDFDocument({ size: "A4", margin: PAGE_MARGIN, bufferPages: true });
}

/**
 * Draws the shared report header: store name, report title, an optional
 * subtitle (date/date-range), and "Generated" metadata. Returns the y
 * position where body content should start.
 */
function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle: string, meta: PdfMeta): number {
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#1f2937").text(shopName(), PAGE_MARGIN, PAGE_MARGIN);
  doc.font("Helvetica-Bold").fontSize(13).fillColor("#4f46e5").text(title, PAGE_MARGIN, doc.y + 2);
  if (subtitle) {
    doc.font("Helvetica").fontSize(10).fillColor("#374151").text(subtitle, PAGE_MARGIN, doc.y + 2);
  }

  const generatedAt = new Date().toLocaleString("en-GB");
  doc.font("Helvetica").fontSize(8.5).fillColor("#6b7280");
  doc.text(`Generated: ${generatedAt}`, PAGE_MARGIN, doc.y + 6);
  if (meta.generatedByName) {
    doc.text(`Generated by: ${meta.generatedByName}`, PAGE_MARGIN, doc.y + 1);
  }

  doc.moveTo(PAGE_MARGIN, doc.y + 8).lineTo(PAGE_MARGIN + CONTENT_WIDTH, doc.y + 8).strokeColor("#e5e7eb").stroke();
  doc.fillColor("#000");
  return doc.y + 16;
}

/** Adds page numbers ("Page X of Y") to every buffered page. Call once, right before returning the doc. */
function addPageNumbers(doc: PDFKit.PDFDocument): void {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.font("Helvetica").fontSize(8).fillColor("#9ca3af");
    doc.text(`Page ${i - range.start + 1} of ${range.count}`, PAGE_MARGIN, FOOTER_Y, {
      width: CONTENT_WIDTH,
      align: "center",
    });
    doc.text(shopName(), PAGE_MARGIN, FOOTER_Y, { width: CONTENT_WIDTH, align: "left" });
  }
}

/**
 * Draws a section title, then a bordered table with a header row.
 * Paginates automatically, redrawing the header row on each new page.
 */
function drawTable(doc: PDFKit.PDFDocument, sectionTitle: string | null, columns: TableColumn[], rows: TableRow[]): void {
  const rowHeight = 18;
  const bottomLimit = 740;

  const drawTableHeader = () => {
    const y = doc.y;
    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, rowHeight).fill("#4f46e5");
    let x = PAGE_MARGIN;
    doc.font("Helvetica-Bold").fontSize(9).fillColor("#ffffff");
    for (const col of columns) {
      doc.text(col.label, x + 6, y + 5, { width: col.width - 10, align: col.align ?? "left" });
      x += col.width;
    }
    doc.fillColor("#000");
    doc.y = y + rowHeight;
  };

  if (sectionTitle) {
    if (doc.y > bottomLimit - 30) doc.addPage();
    doc.font("Helvetica-Bold").fontSize(11).fillColor("#1f2937").text(sectionTitle, PAGE_MARGIN, doc.y);
    doc.moveDown(0.3);
  }

  drawTableHeader();

  for (const row of rows) {
    if (doc.y > bottomLimit) {
      doc.addPage();
      drawTableHeader();
    }
    const y = doc.y;
    if (row.highlight) {
      doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, rowHeight).fill("#f5f3ff");
    }
    let x = PAGE_MARGIN;
    doc.font(row.bold ? "Helvetica-Bold" : "Helvetica").fontSize(9).fillColor("#1f2937");
    for (let i = 0; i < columns.length; i++) {
      const col = columns[i];
      doc.text(row.cells[i] ?? "", x + 6, y + 5, { width: col.width - 10, align: col.align ?? "left" });
      x += col.width;
    }
    doc.moveTo(PAGE_MARGIN, y + rowHeight).lineTo(PAGE_MARGIN + CONTENT_WIDTH, y + rowHeight).strokeColor("#e5e7eb").stroke();
    doc.fillColor("#000");
    doc.y = y + rowHeight;
  }
  doc.moveDown(0.8);
}

/* ────────────────────────────────────────────────────────────────────────
 * Reconciliation (Sales Reconciliation) report
 * ──────────────────────────────────────────────────────────────────────── */

export async function renderReconciliationReportPdf(record: ReconciliationRecord, meta: PdfMeta = {}): Promise<Buffer> {
  const doc = newDocument();
  const dateStr = fmtDateStr(record.date);

  doc.y = drawHeader(doc, "Sales Reconciliation Report", `Date: ${dateStr}`, meta);

  doc.font("Helvetica").fontSize(9).fillColor("#374151");
  const attribution: string[] = [];
  if (record.committedByName) attribution.push(`Committed by: ${record.committedByName}${record.committedAt ? " on " + record.committedAt.toLocaleString("en-GB") : ""}`);
  if (record.adminSubmittedByName) attribution.push(`Admin reviewed by: ${record.adminSubmittedByName}${record.adminSubmittedAt ? " on " + record.adminSubmittedAt.toLocaleString("en-GB") : ""}`);
  for (const line of attribution) doc.text(line);
  if (attribution.length) doc.moveDown(0.6);
  doc.fillColor("#000");

  const columns: TableColumn[] = [
    { label: "Field", width: CONTENT_WIDTH * 0.62 },
    { label: "Amount", width: CONTENT_WIDTH * 0.38, align: "right" },
  ];

  drawTable(doc, "Credit Card", columns, [
    { cells: ["Manual Card Amount", fmtGBP(record.manualCardAmount)] },
    { cells: ["Card Amount", fmtGBP(record.cardAmount)] },
  ]);
  drawTable(doc, "Cash", columns, [
    { cells: ["Last Safe", fmtGBP(record.lastSafe)] },
    { cells: ["Safe Drop Amount", fmtGBP(record.safeDropAmount)] },
  ]);
  drawTable(doc, "Deductions", columns, [
    { cells: ["Cashback", fmtGBP(record.cashback)] },
    { cells: ["Paypoint Payout", fmtGBP(record.paypointPayout)] },
    { cells: ["Instant Lottery Payout", fmtGBP(record.instantLotteryPayout)] },
    { cells: ["Lottery Payout", fmtGBP(record.lotteryPayout)] },
    { cells: ["News Voucher", fmtGBP(record.newsVoucher)] },
    { cells: ["DD Point", fmtGBP(record.ddPoint)] },
  ]);
  drawTable(doc, "Supplier Payout", columns, [["Supplier Payout", fmtGBP(record.supplierInvoicesTotal)]].map((c) => ({ cells: c })));
  drawTable(doc, "Instant Lottery", columns, [
    { cells: ["Total Count", String(record.instantLotteryTotalCount)] },
    { cells: ["Total Sales", fmtGBP(record.instantLotteryTotalSales)] },
  ]);
  drawTable(doc, "Lottery", columns, [{ cells: ["Lottery Value", fmtGBP(record.lotteryValue)] }]);
  drawTable(doc, "Paypoint", columns, [{ cells: ["Paypoint Value", fmtGBP(record.paypointValue)] }]);

  drawTable(doc, "Totals", columns, [
    { cells: ["Summary Total", fmtGBP(record.summaryTotal)], bold: true },
    { cells: ["Z-Report Total", fmtGBP(record.zReportTotal)], bold: true },
    { cells: ["Difference", fmtGBP(record.difference)], bold: true, highlight: true },
  ]);

  if (record.staffNotes) {
    doc.font("Helvetica-Bold").fontSize(10).text("Staff Notes", PAGE_MARGIN, doc.y);
    doc.font("Helvetica").fontSize(9).text(record.staffNotes, { width: CONTENT_WIDTH });
    doc.moveDown(0.5);
  }
  if (record.adminNotes) {
    doc.font("Helvetica-Bold").fontSize(10).text("Admin Notes", PAGE_MARGIN, doc.y);
    doc.font("Helvetica").fontSize(9).text(record.adminNotes, { width: CONTENT_WIDTH });
  }

  addPageNumbers(doc);
  return collectPdf(doc);
}

/**
 * Multi-date reconciliation report — one continuous document covering a
 * date range, rather than one PDF per date. Used when a report spans more
 * than one day but the caller wants a single combined file (e.g. Excel's
 * PDF sibling).
 */
export async function renderReconciliationRangeReportPdf(
  records: ReconciliationRecord[],
  fromDateStr: string,
  toDateStr: string,
  meta: PdfMeta = {},
): Promise<Buffer> {
  const doc = newDocument();
  doc.y = drawHeader(doc, "Sales Reconciliation Report", `Date range: ${fromDateStr} to ${toDateStr}`, meta);

  const columns: TableColumn[] = [
    { label: "Date", width: CONTENT_WIDTH * 0.22 },
    { label: "Summary Total", width: CONTENT_WIDTH * 0.26, align: "right" },
    { label: "Z-Report Total", width: CONTENT_WIDTH * 0.26, align: "right" },
    { label: "Difference", width: CONTENT_WIDTH * 0.26, align: "right" },
  ];

  let grandSummary = 0;
  let grandZ = 0;
  let grandDiff = 0;
  const rows: TableRow[] = records.map((r) => {
    grandSummary += Number(r.summaryTotal);
    grandZ += Number(r.zReportTotal);
    grandDiff += Number(r.difference);
    return {
      cells: [fmtDateStr(r.date), fmtGBP(r.summaryTotal), fmtGBP(r.zReportTotal), fmtGBP(r.difference)],
    };
  });
  rows.push({
    cells: ["Grand Total", fmtGBP(grandSummary), fmtGBP(grandZ), fmtGBP(grandDiff)],
    bold: true,
    highlight: true,
  });

  drawTable(doc, null, columns, rows);

  addPageNumbers(doc);
  return collectPdf(doc);
}

/* ────────────────────────────────────────────────────────────────────────
 * Z-Report bill (raw email body, wrapped in the shared header/footer)
 * ──────────────────────────────────────────────────────────────────────── */

export async function renderZReportBillPdf(date: Date, emailBody: string | null, meta: PdfMeta = {}): Promise<Buffer> {
  const doc = newDocument();
  const dateStr = fmtDateStr(date);

  doc.y = drawHeader(doc, "Z-Report Bill", `Date: ${dateStr}`, meta);

  doc.font("Courier").fontSize(9).fillColor("#1f2937");
  doc.text(emailBody ?? "No Z-report email found for this date.", PAGE_MARGIN, doc.y, { width: CONTENT_WIDTH });

  addPageNumbers(doc);
  return collectPdf(doc);
}

/* ────────────────────────────────────────────────────────────────────────
 * Supplier Payout report — grouped by supplier, range-based
 * ──────────────────────────────────────────────────────────────────────── */

export interface SupplierPayoutInvoiceRow {
  date: string;
  supplierName: string;
  invoiceNo: string;
  value: number;
  enteredBy: string | null;
}

export type SupplierPayoutGroupBy = "supplier" | "date";

export async function renderSupplierPayoutPdf(
  invoices: SupplierPayoutInvoiceRow[],
  fromDateStr: string,
  toDateStr: string,
  meta: PdfMeta = {},
  groupBy: SupplierPayoutGroupBy = "supplier",
): Promise<Buffer> {
  const doc = newDocument();
  doc.y = drawHeader(doc, "Supplier Payout Report", `Date range: ${fromDateStr} to ${toDateStr}`, meta);

  if (invoices.length === 0) {
    doc.font("Helvetica").fontSize(10).text("No supplier invoices found for this range.", PAGE_MARGIN, doc.y);
    addPageNumbers(doc);
    return collectPdf(doc);
  }

  let grandTotal = 0;

  if (groupBy === "date") {
    // By Date — group by date, list each supplier's payout within that
    // date, no cross-date supplier subtotal, just that date's line items.
    const byDate = new Map<string, SupplierPayoutInvoiceRow[]>();
    for (const inv of invoices) {
      const list = byDate.get(inv.date) ?? [];
      list.push(inv);
      byDate.set(inv.date, list);
    }

    const columns: TableColumn[] = [
      { label: "Supplier", width: CONTENT_WIDTH * 0.32 },
      { label: "Invoice No.", width: CONTENT_WIDTH * 0.23 },
      { label: "Entered By", width: CONTENT_WIDTH * 0.22 },
      { label: "Value", width: CONTENT_WIDTH * 0.23, align: "right" },
    ];

    const dates = Array.from(byDate.keys()).sort((a, b) => a.localeCompare(b));
    for (const date of dates) {
      const rows = byDate.get(date)!;
      let dateTotal = 0;
      const tableRows: TableRow[] = rows.map((r) => {
        dateTotal += r.value;
        return { cells: [r.supplierName, r.invoiceNo, r.enteredBy ?? "—", fmtGBP(r.value)] };
      });
      tableRows.push({
        cells: ["", "", "Date Total", fmtGBP(dateTotal)],
        bold: true,
        highlight: true,
      });
      grandTotal += dateTotal;
      drawTable(doc, `Date: ${date}`, columns, tableRows);
    }
  } else {
    // By Supplier — group by supplier, list each date's amount within, then
    // a supplier total.
    const bySupplier = new Map<string, SupplierPayoutInvoiceRow[]>();
    for (const inv of invoices) {
      const list = bySupplier.get(inv.supplierName) ?? [];
      list.push(inv);
      bySupplier.set(inv.supplierName, list);
    }

    const columns: TableColumn[] = [
      { label: "Date", width: CONTENT_WIDTH * 0.18 },
      { label: "Invoice No.", width: CONTENT_WIDTH * 0.27 },
      { label: "Entered By", width: CONTENT_WIDTH * 0.27 },
      { label: "Value", width: CONTENT_WIDTH * 0.28, align: "right" },
    ];

    const supplierNames = Array.from(bySupplier.keys()).sort((a, b) => a.localeCompare(b));
    for (const supplierName of supplierNames) {
      const rows = bySupplier.get(supplierName)!;
      let supplierTotal = 0;
      const tableRows: TableRow[] = rows.map((r) => {
        supplierTotal += r.value;
        return { cells: [r.date, r.invoiceNo, r.enteredBy ?? "—", fmtGBP(r.value)] };
      });
      tableRows.push({
        cells: ["", "", "Supplier Total", fmtGBP(supplierTotal)],
        bold: true,
        highlight: true,
      });
      grandTotal += supplierTotal;
      drawTable(doc, `Supplier: ${supplierName}`, columns, tableRows);
    }
  }

  if (doc.y > 700) doc.addPage();
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#1f2937").text(`Grand Total: ${fmtGBP(grandTotal)}`, PAGE_MARGIN, doc.y + 6);

  addPageNumbers(doc);
  return collectPdf(doc);
}
